[package]
name = "intelli_bot"
version = "0.1.0"
edition = "2021"

[dependencies]

tokio = {version = "1.0", features = ["full"]}  #Async runtime
tokio-tungstenite = "0.17"
reqwest = {version = "0.11", features = ["json"]}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"  #JSON parsing
serde_urlencoded = "0.7"
futures-util = "0.3"
sha2 = "0.10"
hmac = "0.12"
hex = "0.4"
log = "0.4"
chrono = "0.4"  #Timestamp handling
dotenv = "0.15.0" #Includes .env file for sensitive data handling
barter            = "0.12.2"   # barter core
barter-data       = "0.10.1"   # public market data streams
barter-execution  = "0.5.3"    # order execution & account feeds
barter-integration = "0.9.1"   # REST/WebSocket exchange integrations