[exchange.rate_limiter]
request_per_minute = 60
brust_limit = 10

[traing]
symbols = ["BTCUSDT", "ETHUSDT"]
base_currency = "BTC"
quote_currency = "USDT"
timeframe = "1hr"
max_position = 10
max_position_size = 0.10
max_drawdown = 0.1

[risk]
max_risk_per_trade = 0.02
stop_loss_percentage = 0.05
take_profit_percentage = 0.1
max_daily_loss = 0.15

[strategy]
name = "mean_reversion"
parameters = { lookback = 14, threshold = 1.5 }